version: 2.1.{build}-{branch}
os:
  - Visual Studio 2015
environment:
  installerVersion: 2.1.$(APPVEYOR_BUILD_NUMBER)
  pippo: Pluto
#before_build:
#  - msbuild HelloWorld.proj /p:BuildVersion=%installerVersion% /v:diag /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
build:
  project: DumpAllEvaluatedProperties .proj
