version: 2.1.{build}-{branch}
os:
  - Visual Studio 2015
environment:
  pippo: Pluto
build:
  - msbuild HelloWorld.proj /v:diag /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"